FROM --platform=arm64 python:3.10-alpine

WORKDIR /app

ADD requirements.txt .
RUN pip install -r ./requirements.txt

ADD load_balancer.py .
ADD util.py .
ADD primary_load_balancer.py .

ENTRYPOINT ["python"]

CMD ["-u", "./primary_load_balancer.py"]